import { useMemo, useState } from "react";
import type { CV, SpotifyItem } from "../../lib/cvTypes";
import { SectionHeader } from "../layout/SectionHeader";
import { Reveal } from "../ui/Reveal";

type SpotifyKind = "album" | "playlist" | "track";

type Props = {
  cv: CV;
  height?: number;
  initialIndex?: number;
};

function toSpotifyEmbedUrl(url: string): string | null {
  try {
    const u = new URL(url.trim());
    if (!/open\.spotify\.com$/i.test(u.hostname)) return null;

    const parts = u.pathname.split("/").filter(Boolean);
    if (parts.length < 2) return null;

    const kind = parts[0] as SpotifyKind;
    const id = parts[1];
    if (!["album", "playlist", "track"].includes(kind)) return null;

    return `https://open.spotify.com/embed/${kind}/${id}`;
  } catch {
    return null;
  }
}

export function SpotifySection({ cv, height = 352, initialIndex = 0 }: Props) {
  const spotify = cv.media?.spotify;
  const items: SpotifyItem[] = spotify?.items ?? [];

  const [index, setIndex] = useState(() => {
    const i = Number.isFinite(initialIndex) ? initialIndex : 0;
    return Math.min(Math.max(i, 0), Math.max(items.length - 1, 0));
  });

  const current = items[index];

  const embedSrc = useMemo(() => {
    if (!current) return null;
    return toSpotifyEmbedUrl(current.url);
  }, [current]);

  const canNav = items.length > 1;

  const goPrev = () => canNav && setIndex((i) => (i - 1 + items.length) % items.length);
  const goNext = () => canNav && setIndex((i) => (i + 1) % items.length);

  if (!items.length) return null;

  const title = spotify?.title ?? "DJ Dev Studio — Soundtrack";
  const subtitle = spotify?.subtitle ?? "Music generated by me — pick one and press play.";

  return (
    <section className="py-16 md:py-20" id="music">
      <SectionHeader eyebrow="After hours" title={title} desc={subtitle} />

      <Reveal>
        <div className="panel grid gap-6 p-5 md:grid-cols-[1fr_1.4fr] md:p-6">
          <div className="flex flex-col">
            <p className="field-label">Now playing</p>
            <p className="font-display text-2xl font-semibold text-fg">{current?.title ?? "—"}</p>
            {current?.note ? <p className="mt-2 text-sm text-muted">{current.note}</p> : null}

            <div className="mt-6 flex items-center gap-2">
              <button type="button" onClick={goPrev} disabled={!canNav} className="icon-btn" aria-label="Previous">
                <span aria-hidden="true">←</span>
              </button>
              <span className="min-w-12 text-center font-display text-sm tabular-nums text-subtle">
                {index + 1}/{items.length}
              </span>
              <button type="button" onClick={goNext} disabled={!canNav} className="icon-btn" aria-label="Next">
                <span aria-hidden="true">→</span>
              </button>
            </div>

            <ul className="mt-6 space-y-1">
              {items.map((it, i) => (
                <li key={it.id}>
                  <button
                    type="button"
                    onClick={() => setIndex(i)}
                    aria-current={i === index ? "true" : undefined}
                    className={`flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left text-sm transition hover:bg-surface-2 ${
                      i === index ? "bg-surface-2 text-fg" : "text-muted"
                    }`}
                  >
                    <span className="w-5 font-display text-xs tabular-nums text-subtle">{String(i + 1).padStart(2, "0")}</span>
                    <span className="truncate">{it.title}</span>
                    {i === index ? <span className="pulse-dot ml-auto shrink-0" aria-hidden="true" /> : null}
                  </button>
                </li>
              ))}
            </ul>

            <p className="mt-auto pt-6 text-xs text-subtle">
              Browsers usually block autoplay — press Play once in the player.
            </p>
          </div>

          <div>
            {!embedSrc ? (
              <div className="tone-badge tone-badge--amber rounded-2xl border p-4 text-sm">
                Invalid Spotify URL for: <span className="font-semibold">{current?.title}</span>
                <div className="mt-2 text-xs opacity-80">Use open.spotify.com album/playlist/track URL.</div>
              </div>
            ) : (
              <div className="overflow-hidden rounded-2xl border border-line bg-bg-elev">
                <iframe
                  title={`Spotify player: ${current.title}`}
                  src={embedSrc}
                  width="100%"
                  height={height}
                  className="block"
                  allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
                  loading="lazy"
                />
              </div>
            )}
          </div>
        </div>
      </Reveal>
    </section>
  );
}
